# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: blog-junjizhi-com
google_analytics: UA-150349974-1
title: Junji Zhi

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Junji's Blog

description: Junji's Blog
author:
  name: Junji Zhi
  email: contact@junjizhi.com
  github: junjizhi
  twitter: junjizhi
  bio: Software Engineer. @hockeystick.co. Ex-500px.

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
